### ISSUE TITLE
FR: Rename feature 'certificates'

### ISSUE THREAD

**Issue by ThomasMinor** [dodevops/cloudcontrol#133]
Since the feature _certificates_ provides a means to add _trusted certificate authorities_ to the CloudControl environment, the feature name should also reflect this purpose.

Please change the name og the feature to _ca_certificates_ or _tca_.

Please add your opinions

**Comment by dploeger** [comment]
Hm. We need to think this through as it is a breaking change. They're still certificates, but certificates of CAs... I don't know.

**Comment by ThomasMinor** [comment]
I suggest to add the new name and deprecate the old one.
Then we could perform the breaking change release after some more or urgent breaking changes have to be made.
