### ISSUE TITLE
FR: Add cmctl (from certmanager) utility for certificate management

### ISSUE THREAD

**Issue by salami738** [dodevops/cloudcontrol#140]
At first: thanks for creating cloudcontrol. It is useful for us!

I would like to suggest the cmctl tool for integration into cloudcontrol.
Source: https://cert-manager.io/docs/reference/cmctl/

This makes it much easier, for example, to renew letsencrypt certificates before they expire.
Example:

```
./cmctl_linux_amd64 renew -n myNamespace myCertificateName
Manually triggered issuance of Certificate myNamespace/myCertificateName
```

**Comment by dploeger** [comment]
Released in 7.0.0
