### ISSUE TITLE
jq tools

### ISSUE THREAD

**Issue by mlauke** [dodevops/cloudcontrol#4]
hi,

need the >jq tool installed.... at least to use it for initial setup of AWS IAM ;)
i.e.
`aws iam create-policy ... | jq -r ....`

is it possible to add it during init?

**Comment by dploeger** [comment]
Adding jq as a feature seems a good idea. However, in the meantime you can work around this using

    sudo yum install jq

for the AWS and

    sudo apk add jq

for the Azure flavour.
