### ISSUE TITLE
Feature: certificates

### ISSUE THREAD

**Issue by timdeluxe** [dodevops/cloudcontrol#40]
As discussed with @dploeger on a call:

- add "certificates" feature
- expects a bind mounted folder, should fail if folder not there
- looks for *.pem files in that folder
- adds it to the certs to the root-ca collection specific to the flavours base-image OS way

**Comment by dploeger** [comment]
Also, use a feature parameter for the mountpoint, but defaul to something like e.g. /certificates

**Comment by timdeluxe** [comment]
Why can't it be something "we" define in the container?

**Comment by dploeger** [comment]
We can, but it should be configurable IMHO. It's always better to have things configurable, with a sensible default.
