### ISSUE TITLE
FR: Offer installation option for Tanzu CLI

### ISSUE THREAD

**Issue by ThomasMinor** [dodevops/cloudcontrol#87]
# FeatureRequest
VMWare Tanzu offers a [Tanzu CLI and other tools](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.5/vmware-tanzu-kubernetes-grid-15/GUID-install-cli.html) which provide support for the work with the Tanzu resources.

Please implement the installation as a feature for the Tanzu flavor.

**Comment by dploeger** [comment]
Does it make sense to add this as a feature so it can be used from all flavours or directly embed it in the Tanzu flavour?

**Comment by ThomasMinor** [comment]
Hmm, do you mean like an install packages feature which leads to additional custom package installation in the image?
That would then also be an option if the opinionated features of this project don't fit the users needs.

**Comment by dploeger** [comment]
No I meant: we could either implement a new feature that installs the Tanzu CLI OR we can directly install them in the Flavour-Initscript of the Tanzu flavour (because it might not make sense for the AWS or Azure flavour for example).

We might add an environment variable for the flavour to install or not install them if people don't want them for example.

**Comment by ThomasMinor** [comment]
I'd implement it as an option to the existing Tanzu feature.
While writing this: for copy actions it might also be a nice feature for the use with other providers.
Let's talk about it.

**Comment by ThomasMinor** [comment]
We agreed on adding this feature as an option to the TANZU Flavour.
Additional ad optional implementation as a feature is not part of this issue.

**Comment by dploeger** [comment]
Actually, adding it as a feature might be better because features can be tested already and the cli might be of interest in other flavours as well (i.e. simple)

**Comment by dploeger** [comment]
Fixed in #156
